[package]
name = "miden-assembly"
version = "0.9.1"
description = "Miden VM assembly language"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
documentation = "https://docs.rs/miden-assembly/0.9.1"
categories = ["compilers", "no-std"]
keywords = ["assembler", "assembly", "language", "miden"]
edition = "2021"
rust-version = "1.75"

[lib]
bench = false
doctest = false

[features]
default = ["std"]
std = ["vm-core/std"]

[dependencies]
num_enum = "0.7"
tracing = { version = "0.1", default-features = false, features = ["attributes"] }
vm-core = { package = "miden-core", path = "../core", version = "0.9", default-features = false }
web-sys = { version = "0.3", features = ["console"] }
# console_error_panic_hook = "0.1.7"
# talc = "4.4.1"
# spin = "0.9.8"